apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/immxmmi/k8s-scale-test.git
    targetRevision: HEAD
    path: knative/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true