apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-demo-scaledobject
  namespace: keda-demo
spec:
  scaleTargetRef:
    name: keda-demo
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-kube-prometheus-prometheus.prometheus:9090
        metricName: http_requests_total
        threshold: "5"
        query: rate(http_requests_total{job="keda-demo"}[1m])