apiVersion: v1
kind: Service
metadata:
  name: keda-demo
  namespace: keda-demo
spec:
  selector:
    app: keda-demo
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: keda-demo-keda-http-interceptor-proxy
  namespace: keda-demo
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  ports:
    - port: 8080
      targetPort: 8080