apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: keda-demo-http
  namespace: keda-demo
spec:
  hosts:
    - keda-demo.local
  scaleTargetRef:
    name: keda-demo
    kind: Deployment
    apiVersion: apps/v1
    service: keda-demo
    port: 80
  replicas:
    min: 0    # Scale down to 0 pods when no traffic.
    max: 10   # Maximum of 10 pods during high traffic.
  scaledownPeriod: 10  # After scaling up, if traffic stays below threshold for 10s, scale down.
  scalingMetric:
    requestRate:
      granularity: 1s  # Evaluate traffic in 1-second intervals.
      targetValue: 1   # Desired average is 1 request/sec.
      window: 1m       # Calculate average over 1-minute window.
# ---
# 📘 Example behavior:
# If a user sends requests and then stops,
# KEDA will wait until the average request rate over 1 minute drops below 1 request/sec.
# If that low average continues for at least 10 seconds,
# KEDA will scale the deployment down to 0 pods.