apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: keda-demo-http
  namespace: keda-demo
spec:
  hosts:
    - keda-demo.local
  scaleTargetRef:
    name: keda-demo
    kind: Deployment
    apiVersion: apps/v1
    service: keda-demo
    port: 80
  replicas:
    min: 0
    max: 10
  scaledownPeriod: 10
  scalingMetric:
    requestRate:
      granularity: 1s
      targetValue: 1
      window: 1m