apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: keda-demo-http
  namespace: keda-demo
spec:
  hosts:
    - keda-demo.example.com
  scaleTargetRef:
    name: keda-demo
    kind: Deployment
    apiVersion: apps/v1
    service: keda-demo
    port: 80
  targetPendingRequests: 1
  scaledownPeriod: 30
  replicas:
    min: 0
    max: 10