name: CI/CD for Kubernetes Scale

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_TAG: ${{ github.ref_name }}-latest
  BRANCH_TAG: ${{ github.ref_name }}-latest
  DOCKER_APPS_PATH: ci/apps
  HELM_CHARTS_PATH: ci/charts
  HELM_UMBRELLA_CHARTS_PATH: ci/charts-umbrella

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' || contains(github.event.head_commit.message, 'ci/apps/') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & Push All App Images
        run: |
          for dir in ${{ env.DOCKER_APPS_PATH }}/*; do
            name=$(basename "$dir")
            base=${{ env.REGISTRY }}/puzzle-${name}
            docker build -t "$base:${{ env.IMAGE_TAG }}" -t "$base:${{ env.BRANCH_TAG }}" -t "$base:latest" -f "$dir/Dockerfile" "$dir"
            docker push "$base:${{ env.IMAGE_TAG }}"
            docker push "$base:${{ env.BRANCH_TAG }}"
            docker push "$base:latest"
          done